name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}
  RELEASE_VER: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create Archive
        run: |
          mkdir "${PLUGIN_NAME}"
          cp -r main.js manifest.json "${PLUGIN_NAME}"
          zip -r "${PLUGIN_NAME}".zip "${PLUGIN_NAME}"

      - name: Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=${RELEASE_VER##*/}
          gh release create "$TAG_NAME" main.js manifest.json "$PLUGIN_NAME".zip -t "$TAG_NAME" 